name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
            ffmpeg \
            libx11-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libgles2-mesa-dev \
            libalut-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxxf86vm-dev
        go install golang.org/x/tools/cmd/deadcode@latest
    - name: Install doom wad
      run: wget https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/doom1.wad
    - name: Run tests (64-bit)
      run: ./run_tests.sh
    - name: Run tests (32-bit)
      run: |
        export GOOS=linux
        export GOARCH=386
        ./run_tests.sh
    - name: deadcode
      run: |
        DEAD=$(deadcode ./example/webserver)
        if [ -n "$DEAD" ]; then
          echo "deadcode found the following unused code:"
          echo "$DEAD"
          exit 1
        fi
    - name: Build example
      run: |
        go build -o webserver ./example/webserver
        go build -o ebitengine ./example/ebitengine
    - name: Save the test movie outputs
      uses: actions/upload-artifact@v4
      with:
        name: Test Run Movies
        path: doom_test_Test*.mp4